---
title: "Extracurricular"
---

## Awards 


#### Martha and John Hicks Bursary & Scholarship
Issued by Martha and John Hicks family · Jan 2023

   - A $2500 academic grant given to students with a good academic standing and interest in science.
    
#### Commanding Officer's Certificate of Recognition 
Issued by HMCS Chippawa · Dec 2022

  - Honorary Award given by the Commanding Officer for proving excellent service and demonstrating courage. This award was     granted based on an emergency situation where S3 Patel saved the life of a toddler, returning from a national NRET. 

https://www.instagram.com/p/CmPQNd2uEfo/


#### Canadian Armed Forces Education Scholarship (2018-23)
Issued by Canadian Armed Forces · Sep 2022

  - Scholarship of $2000 given to active serving forces members with good academic standing. Scholarship awarded for 4 consecutive years.
  
#### Vita Health Scholarship (2020-21)
Issued by Vita Health Company Ltd · Sep 2020

  - Two-time recipient of Vita Health Scholarship. Scholarship given to students with an outstanding GPA and innovate research in science.
  
#### Flying Officer George Finkle Memorial Scholarship
Issued by University of Manitoba · Jun 2019

  - Scholarship of $650 granted based on Academics, Military service and leadership qualities
  
#### President's Scholarship
Issued by University of Manitoba · Sep 2018

  - Awarded to student with an academic average of 95% or above for incoming fascial year. Award comes with $1000 monetary value along with other designated benefits within the university.
  
#### Stella Wujek (nee Stella Shandruk) 
Issued by Stella Wujek Funds · Sep 2018

  - Personal scholarship $2500 awarded based on academic merit

#### UM Queen Elizabeth II Entrance Scholarship - Tier 1
Issued by University of Manitoba · Sep 2018

  - Associated with University of Manitoba $3000 scholarship awarded to students with an academic average of 95% or higher. Tier level is associated to the class and designation of top average. Tier 1 is given to elite students with the top average of incoming class. My personal average for the year was 98%.

#### RETSD - Silver Medal Student of the Year
Issued by River East Transcona School Division · Jul 2018

  - Medal awarded to the most prestigious student(s) from top high schools in the school division. In order to qualify for the award, students must be have highest academic average and all-round extracurricular activities. All high schools must select their top student to represent at a divisional level, based on the selection all top candidates compete against each other for Gold and Silver Medal Position. 

https://www.facebook.com/retsd/photos/pb.100063465075792.-2207520000./1814733948619863/?type=3

#### Transcona JaycettesTranscona Jaycettes
Issued by Murdoch MacKay Colligate · Jul 2018

  - Awarded plaque & monetary gift for outstanding leadership and character.

